argentina_nueva/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('inicio.urls','inicio'), namespace='inicio')),
    path('socios/',include(('socios.urls','socios'),namespace='socios')),
    path('productos/',include(('productos.urls','productos'),namespace='productos')),
    #path('proveedores/',include(('proveedores.urls','proveedores'),namespace='proveedores')),
    #path('operaciones/',include(('operaciones.urls','operaciones'),namespace='operaciones')),
]

inicio/urls.py
from django.urls import path, include
from inicio.views import Inicio
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',Inicio.as_view(),name='inicio'),
    path('login/',auth_views.LoginView.as_view(template_name='inicio/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='inicio/login.html'),name='logout'),
]

socios/urls.py
from django.urls import path
from socios.views import SociosView, SociosNuevo

urlpatterns = [
    path('socios', SociosView.as_view(), name='socios_list'),
    path('socios/nuevo',SociosNuevo.as_view(),name = 'socios_nuevo'),
]

socios/models.py
from django.db import models
from django.utils import timezone
from inicio.models import ClaseModelo
# Create your models here.

class Socio(ClaseModelo):
    nombre = models.CharField(
        max_length=100,
        help_text='Nombre del Socio'
    )

    apellido = models.CharField(
        max_length=100,
        help_text='Apellido del Socio'
    )

    email = models.CharField(
        max_length=100,
        help_text='Email del Socio'
    )

    telefono = models.CharField(
        max_length=100,
        help_text='Telefono del Socio'
    )

    fecha_nacimiento = models.DateField()

    dni =models.CharField(
        max_length=15,
        help_text='DNI del Socio',
        unique=True
    )

    fecha_creacion = models.DateTimeField(
            default=timezone.now)

    def __str__(self):
        return '{}'.format(self.dni)
    
    def save(self):
        self.nombre = self.nombre.title()
        self.apellido = self.apellido.title()
        self.email = self.email.lower()
        super(Socio,self).save()

    class Meta:
        verbose_name_plural = "Socios"

socios/forms.py
from django import forms
from socios.models import Socio
from django.conf.locale.en import formats as en_formats
#Formato de Fecha
en_formats.DATE_FORMAT = "%d/%m/%Y"

class SocioForm(forms.ModelForm):
    class Meta:
        model=Socio
        fields = ['nombre','apellido','email','telefono','fecha_nacimiento','dni']
        labels = {'nombre':"Nombre del Socio",
                  'apellido':"Apellido",
                  'email':"Email",
                  'telefono':"Telefono",
                  'fecha_nacimiento':"Fecha de Nacimiento",
                  'dni':"DNI"}
        widget = {'nombre':forms.TextInput(),
                  'apellido':forms.TextInput(),
                  'email':forms.TextInput(),
                  'telefono':forms.TextInput(),
                  'fecha_nacimiento':forms.DateField(),
                  'dni':forms.TextInput()}                
        help_texts = {'nombre':(),
                      'apellido':(),
                      'email':(),
                      'telefono':(),
                      'fecha_nacimiento':(),
                      'dni':(),}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })

socios/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse_lazy
from socios.models import Socio
from django.contrib.auth.mixins import LoginRequiredMixin
from socios.forms import SocioForm

# Create your views here.

class SociosView(LoginRequiredMixin, generic.ListView):
    model = Socio
    template_name = "socios/socios_list.html"
    context_object_name = "obj"
    login_url = 'inicio:login'

class SociosNuevo(generic.CreateView):
    model = Socio
    template_name = "socios/socios_form.html"
    context_object_name = "obj"
    form_class = SocioForm
    success_url = reverse_lazy("socios:socios_list")

socios/templates/socios/socios_form.html
{% extends 'base/base.html' %}
{% block inicio %}

<form method="POST">
    <div class="panel panel-default">
        <div class="panel-heading">
        <h6 class="m-0 font-weight-bold text-primary">Editar o dar de alta nuevo Socio</h6>
        <HR>
        </div>
        <div class="panel-body" >
            {% csrf_token %} <!-- Token de seguridad DJANGO -->
            {{ form.as_p }}
            <HR>
            <button type="submit" class="btn btn-success">Guardar</button>
            &nbsp;&nbsp;
            <a href="{% url 'socios:socios_list' %}" class="btn btn-danger">Cancelar</a>
        </div>
    </div>
</form>

{% endblock inicio %}

{% block scripts_local %}  
 <script>  
  $(function () {  
   $("#id_fecha_nacimiento").datetimepicker({  
       format: 'd/m/Y',  
       timepicker:false  
   });  
  });  
 </script>  
 {% endblock scripts_local %}  

socios/templates/socios/socios_list.html
{% extends 'base/base.html' %}
{% block inicio %}
<a href="{% url 'socios:socios_nuevo' %}" class="btn btn-info"><span class="fa fa-plus-circle"></span>   Nuevo Socio</a>
<HR>
<div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6 class="m-0 font-weight-bold text-primary">Lista de Socios</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <div id="dataTable_wrapper" class="dataTables_wrapper dt-bootstrap4">
        <table class="table table-striped table-bordered dt-responsive nowrap" id="dataTable" width="100%" cellspacing="0" role="grid" aria-describedby="dataTable_info" style="width: 100%;">
        <thead>
            <tr>
                <th>ID</th>
                <th>DNI</th>
                <th>Nombre</th>
                <th>Apellido</th>
                <th>Email</th>
                <th>Telefono</th>
                <th>Fecha Nacimiento</th>
                <th>Fecha Creacion</th>
            </tr>
        </thead>
        <tbody>
            {% for item in obj %}
            <tr>
                <td>{{ item.id }}</td>
                <td>{{ item.dni }}</td>
                <td>{{ item.nombre }}</td>
                <td>{{ item.apellido }}</td>
                <td>{{ item.email }}</td>
                <td>{{ item.telefono }}</td>
                <td>{{ item.fecha_nacimiento }}</td>
                <td>{{ item.fecha_creacion }}</td>
            </tr> 
            {% endfor %}   
        </tbody>
    </div>
    </div>
</div>
</div>
{% endblock inicio %}