argentina_nueva/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('inicio.urls','inicio'), namespace='inicio')),
    path('socios/',include(('socios.urls','socios'),namespace='socios')),
    path('productos/',include(('productos.urls','productos'),namespace='productos')),
    #path('proveedores/',include(('proveedores.urls','proveedores'),namespace='proveedores')),
    #path('operaciones/',include(('operaciones.urls','operaciones'),namespace='operaciones')),
]

inicio/urls.py
from django.urls import path, include
from inicio.views import Inicio
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('',Inicio.as_view(),name='inicio'),
    path('login/',auth_views.LoginView.as_view(template_name='inicio/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='inicio/login.html'),name='logout'),
]

productos/urls.py
from django.urls import path
from productos.views import MarcaView, RubroView, SegmentoView, ProductoView

urlpatterns = [
    path('marca', MarcaView.as_view(), name='marca_list'),
    path('rubro', RubroView.as_view(), name='rubro_list'),
    path('segmento', SegmentoView.as_view(), name='segmento_list'),
    path('producto', ProductoView.as_view(), name='producto_list'),
]

socios/urls.py
from django.urls import path
from socios.views import SociosView, SociosNuevo

urlpatterns = [
    path('socios', SociosView.as_view(), name='socios_list'),
    path('socios/nuevo',SociosNuevo.as_view(),name = 'socios_nuevo'),
]

inicio/models.py
from django.db import models

# Create your models here.

class ClaseModelo(models.Model):
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    fecha_modificacion = models.DateTimeField(auto_now=True)
    fecha_fin = models.DateTimeField(auto_now=False,null=True,blank=True)

    class Meta:
        abstract=True

inicio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class Inicio(LoginRequiredMixin, generic.TemplateView):
    template_name = 'base/base.html'
    login_url = 'inicio:login'

inicio/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Argentina Nueva</title>

  <!-- Custom fonts for this template-->
  <link href="{% static 'base/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'base/css/sb-admin-2.min.css' %}" rel="stylesheet">

  <!-- Custom datatable for this template-->
  <link href="{% static 'base/css/datatables.min.css' %}" rel="stylesheet" type="text/css">
  <link href="{% static 'base/css/DataTables-1.10.20/css/dataTables.bootstrap.min.css' %}" rel="stylesheet" type="text/css">
  
  <!-- Custom datepicker for this template-->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />

</head>

<body id="page-top">

  <!-- Page Wrapper -->
  <div id="wrapper">

    <!-- Sidebar -->
    <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'inicio:inicio' %}">
        <img class="img-logo" src="{% static 'base/img/mutual.png' %}" width="40" height="40"></i>
        <div class="sidebar-brand-text"><sub>Asociación Mutualista</sub><br><strong>Argentina</strong> Nueva</div>
      </a>

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'inicio:inicio' %}">
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Aplicaciones
      </div>

      <!-- Nav Item - Pages Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'socios:socios_list' %}">
          <i class="fas fa-fw fa-user"></i>
          <span>Socios</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
          <i class="fas fa-fw fa-store"></i>
          <span>Productos</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Categorias:</h6>
            <a class="collapse-item" href="{% url 'productos:rubro_list' %}">Rubros</a>
            <a class="collapse-item" href="{% url 'productos:segmento_list' %}">Segmentos</a>
            <a class="collapse-item" href="{% url 'productos:marca_list' %}">Marcas</a>
            <a class="collapse-item" href="{% url 'productos:producto_list' %}">Productos</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Operaciones Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
          <i class="fas fa-fw fa-money-check"></i>
          <span>Operaciones</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Categorias:</h6>
            <a class="collapse-item" href="utilities-color.html">Ventas</a>
            <a class="collapse-item" href="utilities-border.html">Alquileres</a>
            <a class="collapse-item" href="utilities-animation.html">Prestamos</a>
            <a class="collapse-item" href="utilities-other.html">Visitas</a>
          </div>
        </div>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider">

      <!-- Heading -->
      <div class="sidebar-heading">
        Complementos
      </div>

      <!-- Nav Item - Reportes Collapse Menu -->
      <li class="nav-item">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
          <i class="fas fa-fw fa-chart-area"></i>
          <span>Reportes</span>
        </a>
        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
            <h6 class="collapse-header">Listado de Reportes:</h6>
            <a class="collapse-item" href="login.html">Reporte 1</a>
            <a class="collapse-item" href="register.html">Reporte 2</a>
            <a class="collapse-item" href="forgot-password.html">Reporte 3</a>
            <div class="collapse-divider"></div>
            <h6 class="collapse-header">Secundarios: </h6>
            <a class="collapse-item" href="404.html">Reporte 4</a>
            <a class="collapse-item active" href="blank.html">Reporte 5</a>
          </div>
        </div>
      </li>

      <!-- Nav Item - Tables -->
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">
          <i class="fas fa-fw fa-users-cog"></i>
          <span>Administación</span></a>
      </li>

      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>
    <!-- End of Sidebar -->

    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">

      <!-- Main Content -->
      <div id="content">

        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Buscar..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Lautaro Castillo</span>
                <img class="img-profile rounded-circle" src="{% static 'base/img/user01.jpg' %}">
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Perfil
                </a>
                <a class="dropdown-item" href="#">
                  <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                  Administación
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Cerrar Sesion
                </a>
              </div>
            </li>

          </ul>

        </nav>
        <!-- End of Topbar -->

        <!-- Begin Page Content -->
        <div class="container-fluid">

          <!-- Page Heading -->
          {% block inicio %} Inicio {% endblock inicio %}

        </div>
        <!-- /.container-fluid -->

      </div>
      <!-- End of Main Content -->

      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
        </div>
      </footer>
      <!-- End of Footer -->

    </div>
    <!-- End of Content Wrapper -->

  </div>
  <!-- End of Page Wrapper -->

  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">¿Seguro que deseas salir?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Selecciona "Cerrar Sesion" debajo si deseas cerrar tu sesion.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
          <a class="btn btn-primary" href="{% url 'inicio:logout' %}">Cerrar Sesion</a>
        </div>
      </div>
    </div>
  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'base/js/jquery.min.js' %}"></script>
  <script src="{% static 'base/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'base/js/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'base/js/sb-admin-2.min.js' %}"></script>

  <!-- Custom scripts datatable for all pages-->
  <script type="text/javascript" src="{% static 'base/js/datatables.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'base/js/DataTables-1.10.20/js/jquery.dataTables.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'base/js/DataTables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'base/js/DataTables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>

  <script>
    $(document).ready( function () {
        $('#dataTable').DataTable({
            language: { //Traducir informacion de Datatable
        "decimal": "",
        "emptyTable": "No hay información",
        "info": "Mostrando _START_ a _END_ de _TOTAL_ registros",
        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
        "infoFiltered": "(Filtrado de _MAX_ total registros)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Mostrar _MENU_ registros",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": "Buscar:",
        "zeroRecords": "Sin resultados encontrados",
        "paginate": {
            "first": "Primero",
            "last": "Ultimo",
            "next": "Siguiente",
            "previous": "Anterior"
        }
        }
        });
    } );
  </script>
   
  <!-- Custom scripts datetime picker for all pages--> 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
</body>

</html>

{% block scripts_local %}  
{% endblock scripts_local %}  